language: node_js
node_js: '4.3'
cache:
  directories:
    - node_modules
script:
  - npm test
  - make SETTINGS_FILE=settings/chrome-prod.json dist/$(date +'%Y%m%d')-chrome-prod.zip
  - make SETTINGS_FILE=settings/firefox-prod.json dist/$(date +'%Y%m%d')-firefox-prod.xpi
addons:
  artifacts:
    paths:
      # Upload all built extension packages
      - $(ls dist/*.zip dist/*.xpi | tr "\n" ":")
